# GOAL I have to build, test the code for frontend and backend
# then push images to dockerhub
name: CI
on:
  push:
    branches: [main]
jobs:
   frontend:
      runs-on: ubuntu-latest
      steps:
      - name: checkout code
        uses: actions/checkout@v7
      - name: linter setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: npn
          cache-dependency-path: frontend/package-lock.json
      - name: install npn packages
        run: npn ci
      - name: run linter
        run: npn run lint
      - name: run tests
        run: npn run test
       
        
     # - Test
     # - Push
   #backend:
   #  steps:
    #  - Lint
    #  - Build
    #  - Test
    #  - Push
