# Goal - I have to do sast for code
name: code quality
on:
    workflow_call:
jobs:
    sast:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: setup nodejs
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: install frontend dependencies
              run: npm ci
              working-directory: frontend
            - name: run frontend linter
              run: npm run lint
              working-directory: frontend
              continue-on-error: true
            - name: setup go
              uses: actions/setup-go@v4
              with:
                go-version: '1.25'
            - name: run go fmt
              run: go fmt ./...
              working-directory: backend
              continue-on-error: true
            - name: run go vet
              run: go vet ./...
              working-directory: backend
              continue-on-error: true
