# Goal i have to ensure  dependency and ppackages have been audited for security
name: dependency scan
on:
    workflow_call:
jobs:
    dependecny-scan:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: set up go
              uses: actions/setup-go@v4
              with:
                go-version: '1.25'
            - name: check go vulnerabilities
              run: go list -json -m all | nancy sleuth
              working-directory: backend
              continue-on-error: true
            - name: setup nodejs
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: check npm vulnerabilities
              run: npm audit --production
              working-directory: frontend
              continue-on-error: true
