# to run end to end devscops pipleline
name: DevSecOps
on:
    push:
        branches: [dev]
jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secret-scan:
        uses: ./.github/workflows/secret-scan.yml
    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml
    docker-scan:
        uses: ./.github/workflows/docker-scan.yml