# to run end to end devscops pipleline
name: DevSecOps
on:
    push:
        branches: [dev]
jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secret-scane:
        uses: ./.github/workflows/secret-scan.yml