# docker files and docker images are security tested 
name: docker scan
on:
    workflow_call:
jobs:
    dockerfile-lint-and-scan:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                folders: ['backend','frontend']
        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: dockerfile lint
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: ${{ matrix.folders }}/Dockerfile
              continue-on-error: true
            
            - name: build docker image
              run: docker build -t devboard-${{ matrix.folders }}:latest ${{ matrix.folders }}
              continue-on-error: true
            
            - name: trivy scan
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                image-ref: devboard-${{ matrix.folders }}:latest
                format: sarif
                output: trivy-results.sarif
              continue-on-error: true
