# Goal - to ensure no secrest to be leaked in the code
name: secrets-scane
on:
    workflow_call:
jobs:
    scan-secret:
        runs-on: ubuntu:latest
        steps:
            - name: checkout
              uses: actions/checkout@v7
              with:
                fetch-depth: 0
            - name: GitLeaks scanner
              uses: gitleaks/gitleaks-actions@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             